//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitLogicCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitLogicCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LSB: 0 ähnelt.
        /// </summary>
        internal static string lsb0 {
            get {
                return ResourceManager.GetString("lsb0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LSB: 1 ähnelt.
        /// </summary>
        internal static string lsb1 {
            get {
                return ResourceManager.GetString("lsb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 00 ähnelt.
        /// </summary>
        internal static string number00 {
            get {
                return ResourceManager.GetString("number00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 01 ähnelt.
        /// </summary>
        internal static string number01 {
            get {
                return ResourceManager.GetString("number01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 02 ähnelt.
        /// </summary>
        internal static string number02 {
            get {
                return ResourceManager.GetString("number02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 03 ähnelt.
        /// </summary>
        internal static string number03 {
            get {
                return ResourceManager.GetString("number03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 04 ähnelt.
        /// </summary>
        internal static string number04 {
            get {
                return ResourceManager.GetString("number04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 05 ähnelt.
        /// </summary>
        internal static string number05 {
            get {
                return ResourceManager.GetString("number05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 06 ähnelt.
        /// </summary>
        internal static string number06 {
            get {
                return ResourceManager.GetString("number06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 07 ähnelt.
        /// </summary>
        internal static string number07 {
            get {
                return ResourceManager.GetString("number07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 08 ähnelt.
        /// </summary>
        internal static string number08 {
            get {
                return ResourceManager.GetString("number08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 09 ähnelt.
        /// </summary>
        internal static string number09 {
            get {
                return ResourceManager.GetString("number09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10 ähnelt.
        /// </summary>
        internal static string number10 {
            get {
                return ResourceManager.GetString("number10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 11 ähnelt.
        /// </summary>
        internal static string number11 {
            get {
                return ResourceManager.GetString("number11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 12 ähnelt.
        /// </summary>
        internal static string number12 {
            get {
                return ResourceManager.GetString("number12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 13 ähnelt.
        /// </summary>
        internal static string number13 {
            get {
                return ResourceManager.GetString("number13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 14 ähnelt.
        /// </summary>
        internal static string number14 {
            get {
                return ResourceManager.GetString("number14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 15 ähnelt.
        /// </summary>
        internal static string number15 {
            get {
                return ResourceManager.GetString("number15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 16 ähnelt.
        /// </summary>
        internal static string number16 {
            get {
                return ResourceManager.GetString("number16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 17 ähnelt.
        /// </summary>
        internal static string number17 {
            get {
                return ResourceManager.GetString("number17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 18 ähnelt.
        /// </summary>
        internal static string number18 {
            get {
                return ResourceManager.GetString("number18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 19 ähnelt.
        /// </summary>
        internal static string number19 {
            get {
                return ResourceManager.GetString("number19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 29 ähnelt.
        /// </summary>
        internal static string number20 {
            get {
                return ResourceManager.GetString("number20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 21 ähnelt.
        /// </summary>
        internal static string number21 {
            get {
                return ResourceManager.GetString("number21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 22 ähnelt.
        /// </summary>
        internal static string number22 {
            get {
                return ResourceManager.GetString("number22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 23 ähnelt.
        /// </summary>
        internal static string number23 {
            get {
                return ResourceManager.GetString("number23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 24 ähnelt.
        /// </summary>
        internal static string number24 {
            get {
                return ResourceManager.GetString("number24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 25 ähnelt.
        /// </summary>
        internal static string number25 {
            get {
                return ResourceManager.GetString("number25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 26 ähnelt.
        /// </summary>
        internal static string number26 {
            get {
                return ResourceManager.GetString("number26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 27 ähnelt.
        /// </summary>
        internal static string number27 {
            get {
                return ResourceManager.GetString("number27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 28 ähnelt.
        /// </summary>
        internal static string number28 {
            get {
                return ResourceManager.GetString("number28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 29 ähnelt.
        /// </summary>
        internal static string number29 {
            get {
                return ResourceManager.GetString("number29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 30 ähnelt.
        /// </summary>
        internal static string number30 {
            get {
                return ResourceManager.GetString("number30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 31 ähnelt.
        /// </summary>
        internal static string number31 {
            get {
                return ResourceManager.GetString("number31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 32 ähnelt.
        /// </summary>
        internal static string number32 {
            get {
                return ResourceManager.GetString("number32", resourceCulture);
            }
        }
    }
}
